Repository openstreetmap/openstreetmap-website, pull requests merged in 2021-02, with the labels that each got.

#3079 More bootstrap forms
  app/assets/stylesheets/common.scss
  app/views/layouts/map.html.erb
  app/views/messages/_message_summary.html.erb
  app/views/messages/_sent_message_summary.html.erb
  app/views/oauth_clients/index.html.erb
  app/views/site/export.html.erb
  app/views/user_blocks/revoke.html.erb
  app/views/users/account.html.erb
Labels: ui

#2409 Add Docker Compose Support for Development Environment
  .dockerignore
  .github/workflows/docker.yml
  .gitignore
  DOCKER.md
  Dockerfile
  INSTALL.md
  config/boot.rb
  config/docker.database.yml
  docker-compose.yml
  docker/null-island.osm.xml
  docker/postgres/Dockerfile
  docker/postgres/openstreetmap-postgres-init.sh
Labels: changes requested, dx

#3091 Fix unexpected spacing on note buttons when overflowed
  app/assets/stylesheets/common.scss
  app/views/browse/note.html.erb
Labels: changes requested, ui
