Repository openstreetmap/openstreetmap-website, pull requests merged in 2022-11, with the labels that each got.

#3797 Remove references to "The Rails Port"
  CONFIGURE.md
  CONTRIBUTING.md
  DOCKER.md
  INSTALL.md
  README.md
  db/functions/quadtile.c
Labels: dx

#3800 Use rails 7.0 configuration defaults
  config/application.rb
  config/initializers/new_framework_defaults_7_0.rb
Labels: refactor

#3803 Remove more usage of html_safe
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/views/changesets/history.html.erb
  app/views/sessions/_suspended_flash.html.erb
  config/locales/en.yml
Labels: refactor

#3805 Use the mail_to method to construct a mailto link for browse tag values
  app/helpers/browse_tags_helper.rb
  config/locales/en.yml
  test/helpers/browse_tags_helper_test.rb
Labels: refactor

#3676 Display how long until a note will disappear
  app/controllers/api/notes_controller.rb
  app/helpers/note_helper.rb
  app/models/note.rb
  app/views/browse/note.html.erb
  config/locales/en.yml
  test/helpers/note_helper_test.rb
Labels: changes requested
