Repository openstreetmap/openstreetmap-website, pull requests merged in 2022-04, with the labels that each got.

#3523 Rubocop autofix: ambiguous operator precedence
  .rubocop_todo.yml
  app/controllers/geocoder_controller.rb
  app/models/user.rb
  lib/bounding_box.rb
  lib/osm.rb
  lib/rich_text.rb
  lib/short_link.rb
  test/controllers/api/old_nodes_controller_test.rb
  test/lib/short_link_test.rb
Labels: refactor

#3537 Rework common details to avoid awkward line breaks
  app/views/browse/_common_details.html.erb
Labels: ui

#3536 Meaningful and disambiguating class/type labels (from 2012)
  config/locales/en.yml
Labels: changes requested
