Repository openstreetmap/openstreetmap-website, pull requests merged in 2023-10, with the labels that each got.

#4257 Docker: Use `docker compose`
  .github/workflows/docker.yml
  DOCKER.md
  config/docker.database.yml
Labels: changes requested, dx

#4274 Prefer find_by() instead of where().first
  .rubocop.yml
  app/controllers/api/traces_controller.rb
  app/controllers/application_controller.rb
  app/controllers/diary_entries_controller.rb
  app/controllers/traces_controller.rb
  test/controllers/api/traces_controller_test.rb
  test/controllers/diary_entries_controller_test.rb
  test/controllers/friendships_controller_test.rb
  test/controllers/traces_controller_test.rb
  test/models/node_test.rb
  test/models/trace_test.rb
Labels: refactor

#4262 Upgrade to Bootstrap 5.3
  Gemfile
  Gemfile.lock
Labels: ui, dependencies
