Repository openstreetmap/openstreetmap-website, pull requests merged in 2023-11, with the labels that each got.

#4346 Remove global text-align declarations
  app/assets/stylesheets/common.scss
Labels: i18n

#4333 Format right-to-left and bi-di text in OSM tag values
  app/views/browse/_tag.html.erb
Labels: changes requested

#4349 Use friendly_date helpers throughout the site
  app/assets/stylesheets/common.scss
  app/helpers/application_helper.rb
  app/helpers/changesets_helper.rb
  app/helpers/note_helper.rb
  app/views/browse/_common_details.html.erb
  app/views/browse/changeset.html.erb
  app/views/dashboards/_contact.html.erb
  app/views/diary_entries/comments.html.erb
  app/views/issues/index.html.erb
  app/views/notes/show.html.erb
  app/views/traces/_trace.html.erb
  app/views/user_blocks/revoke.html.erb
  config/locales/en.yml
  test/helpers/application_helper_test.rb
  test/helpers/changesets_helper_test.rb
  test/helpers/note_helper_test.rb
  test/helpers/user_blocks_helper_test.rb
Labels: refactor
