Repository openstreetmap/openstreetmap-website, pull requests merged in 2023-03, with the labels that each got.

#3960 Remove some unused translations
  config/locales/en.yml
Labels: i18n

#3961 Add the i18n-tasks gem
  Gemfile
  Gemfile.lock
  config/i18n-tasks.yml
Labels: i18n

#3846 Update OSGB date range for copyright
  config/locales/en.yml
Labels: awaiting upstream

#3962 Remove more raw html from translations
  app/views/confirmations/confirm.html.erb
  app/views/shared/_markdown_help.html.erb
  app/views/site/_potlatch.html.erb
  app/views/site/communities.html.erb
  app/views/site/fixthemap.html.erb
  app/views/users/terms.html.erb
  config/locales/en.yml
Labels: i18n

#3963 Document the procedure to change the copyright attribution page
  CONTRIBUTING.md
Labels: dx

#3981 Remove incorrect language blocks from copyright page
  app/views/site/copyright.html.erb
Labels: bug, i18n

#3982 Use with_locale instead of individual locale overrides
  app/views/site/_about_section.html.erb
  app/views/site/about.html.erb
  app/views/site/copyright.html.erb
  test/controllers/site_controller_test.rb
Labels: refactor, i18n

#3983 Avoid using raw html on the copyright page
  app/views/site/copyright.html.erb
  config/locales/en.yml
Labels: refactor, i18n

#3986 More avoiding using raw html in translations
  app/helpers/changesets_helper.rb
  app/views/browse/_common_details.html.erb
  app/views/browse/changeset.html.erb
  app/views/issues/index.html.erb
  app/views/site/about.html.erb
  config/locales/en.yml
  test/helpers/changesets_helper_test.rb
Labels: refactor, i18n
