Repository openstreetmap/openstreetmap-website, pull requests merged in 2023-06, with the labels that each got.

#3959 Adding information about Serbia sources
  app/views/site/copyright.html.erb
  config/locales/en.yml
Labels: awaiting upstream

#3907 Facelift `offline.html` and use Bootstrap classes for "notifications" under the search bar
  app/assets/stylesheets/common.scss
  app/controllers/site_controller.rb
  app/views/layouts/_flash.html.erb
  app/views/site/edit.html.erb
  app/views/site/offline.html.erb
  test/controllers/accounts_controller_test.rb
  test/controllers/messages_controller_test.rb
  test/controllers/passwords_controller_test.rb
  test/controllers/preferences_controller_test.rb
  test/controllers/profiles_controller_test.rb
  test/controllers/site_controller_test.rb
  test/integration/user_login_test.rb
Labels: changes requested

#4063 Fix test suite to work in non-UK timezones
  test/helpers/application_helper_test.rb
  test/helpers/note_helper_test.rb
Labels: bug, dx
