Repository openstreetmap/openstreetmap-website, pull requests merged in 2024-08, with the labels that each got.

#5076 Add debug gem
  Gemfile
  Gemfile.lock
Labels: dx

#5100 Add overcommit to manage git hooks
  .gitignore
  .overcommit.yml
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: dx

#4587 Move changeset comments feed to resourceful routes
  app/controllers/changeset_comments_controller.rb
  app/controllers/feeds/changeset_comments_controller.rb
  app/views/feeds/changeset_comments/_comment.html.erb
  app/views/feeds/changeset_comments/_comment.rss.builder
  app/views/feeds/changeset_comments/index.rss.builder
  app/views/feeds/changeset_comments/timeout.atom.builder
  app/views/feeds/changeset_comments/timeout.html.erb
  config/locales/en.yml
  config/routes.rb
  test/controllers/changeset_comments_controller_test.rb
  test/controllers/feeds/changeset_comments_controller_test.rb
Labels: changesets

#4565 Reload only element type sections with Turbo frames
  app/assets/javascripts/index.js
  app/controllers/changesets_controller.rb
  app/helpers/browse_helper.rb
  app/views/changesets/_elements.html.erb
  app/views/changesets/_paging_nav.html.erb
  app/views/changesets/show.html.erb
  lib/classic_pagination/pagination_helper.rb
  test/system/changeset_elements_test.rb
Labels: changesets

#5126 Rename Feeds::ChangesetCommentsController to ChangesetComments::FeedsController
  app/abilities/ability.rb
  app/controllers/changeset_comments/feeds_controller.rb
  app/views/changeset_comments/feeds/_comment.html.erb
  app/views/changeset_comments/feeds/_comment.rss.builder
  app/views/changeset_comments/feeds/show.rss.builder
  app/views/changeset_comments/feeds/timeout.atom.builder
  app/views/changeset_comments/feeds/timeout.html.erb
  config/locales/en.yml
  config/routes.rb
  test/controllers/changeset_comments/feeds_controller_test.rb
Labels: refactor
