Repository openstreetmap/openstreetmap-website, pull requests merged in 2024-10, with the labels that each got.

#5245 Move api error handling and timeouts to parent class
  app/controllers/api/capabilities_controller.rb
  app/controllers/api/changeset_comments_controller.rb
  app/controllers/api/changesets_controller.rb
  app/controllers/api/map_controller.rb
  app/controllers/api/messages_controller.rb
  app/controllers/api/nodes_controller.rb
  app/controllers/api/notes_controller.rb
  app/controllers/api/old_elements_controller.rb
  app/controllers/api/permissions_controller.rb
  app/controllers/api/relations_controller.rb
  app/controllers/api/tracepoints_controller.rb
  app/controllers/api/traces_controller.rb
  app/controllers/api/user_blocks_controller.rb
  app/controllers/api/user_preferences_controller.rb
  app/controllers/api/users_controller.rb
  app/controllers/api/versions_controller.rb
  app/controllers/api/ways_controller.rb
  app/controllers/api_controller.rb
Labels: refactor

#4919 Add pull request template
  .github/pull_request_template.md
Labels: enhancement, dx

#5288 Decrease padding between close button and inputs in directions form
  app/views/layouts/_search.html.erb
Labels: ui

#5289 Remove callback from initialize() in note js controller
  app/assets/javascripts/index/note.js
Labels: refactor, javascript

#5284 Note subscriptions db table
  app/controllers/api/notes_controller.rb
  app/models/note.rb
  app/models/note_subscription.rb
  app/models/user.rb
  db/migrate/20241022141247_create_note_subscriptions.rb
  db/structure.sql
  test/controllers/api/notes_controller_test.rb
Labels: api, javascript, notes
