Repository openstreetmap/openstreetmap-website, pull requests merged in 2025-03, with the labels that each got.

#5739 Use location instead of window.location and document.location
  app/assets/javascripts/embed.js.erb
  app/assets/javascripts/index.js
  app/assets/javascripts/index/changeset.js
  app/assets/javascripts/index/directions.js
  app/assets/javascripts/index/history.js
  app/assets/javascripts/index/note.js
  app/assets/javascripts/index/query.js
  app/assets/javascripts/leaflet.map.js
  app/assets/javascripts/login.js
  app/assets/javascripts/matomo.js
  app/assets/javascripts/osm.js.erb
  app/assets/javascripts/router.js
  app/assets/javascripts/welcome.js
  test/javascripts/osm_test.js
Labels: javascript

#5740 Set the environment variable in teaspoon example
  CONTRIBUTING.md
Labels: dx

#5742 Replace $(document).ready(...) with $(...)
  app/assets/javascripts/application.js
  app/assets/javascripts/auth_providers.js
  app/assets/javascripts/diary_entry.js
  app/assets/javascripts/edit/id.js.erb
  app/assets/javascripts/fixthemap.js
  app/assets/javascripts/index.js
  app/assets/javascripts/login.js
  app/assets/javascripts/matomo.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/social_share_button.js
  app/assets/javascripts/user.js
  app/assets/javascripts/welcome.js
Labels: javascript

#5767 Load more reporting users when clicking "and n more" in issues table
  app/controllers/issues/reporters_controller.rb
  app/controllers/issues_controller.rb
  app/views/issues/_page.html.erb
  app/views/issues/reporters/_reporters.html.erb
  app/views/issues/reporters/index.html.erb
  config/locales/en.yml
  config/routes.rb
  test/controllers/issues/reporters_controller_test.rb
Labels: moderation

#5493 Label administrative boundaries by real-world designation
  app/assets/javascripts/index/query.js
  app/controllers/geocoder_controller.rb
  config/locales/en.yml
Labels: changes requested

#5402 Add user profile heatmap visualization for contributions
  app/assets/config/manifest.js
  app/assets/javascripts/heatmap.js
  app/assets/stylesheets/common.scss
  app/controllers/users_controller.rb
  app/views/users/show.html.erb
  config/locales/en.yml
  package.json
  test/controllers/users_controller_test.rb
  yarn.lock
Labels: big-pr

#4872 Show changeset element counts using badges
  app/helpers/browse_helper.rb
  app/views/changesets/_paging_nav.html.erb
  config/locales/en.yml
Labels: ui, changesets

#5846 Update strong_migrations to be compatible with rails 8
  Gemfile
  Gemfile.lock
Labels: bug
