Repository openstreetmap/openstreetmap-website, pull requests merged in 2025-01, with the labels that each got.

#5464 Add OldElementsController base class
  app/controllers/old_elements_controller.rb
  app/controllers/old_nodes_controller.rb
  app/controllers/old_relations_controller.rb
  app/controllers/old_ways_controller.rb
  app/views/old_elements/_actions.html.erb
  app/views/old_elements/index.html.erb
  app/views/old_nodes/show.html.erb
  app/views/old_relations/show.html.erb
  app/views/old_ways/show.html.erb
  config/locales/en.yml
  test/controllers/old_nodes_controller_test.rb
  test/controllers/old_relations_controller_test.rb
  test/controllers/old_ways_controller_test.rb
Labels: refactor

#5486 Update documentation to avoid erb_lint deprecations
  CONTRIBUTING.md
Labels: dx

#5433 Resourceful routes for users api
  app/abilities/api_ability.rb
  app/controllers/api/users/traces_controller.rb
  app/controllers/api/users_controller.rb
  app/views/api/users/traces/index.builder
  config/routes.rb
  test/controllers/api/users/traces_controller_test.rb
  test/controllers/api/users_controller_test.rb
Labels: refactor, api

#5500 Install add/remove event listeners directly on note layer
  app/assets/javascripts/index/layers/notes.js
Labels: javascript

#5261 Modify the way "Friends" are added
  app/abilities/ability.rb
  app/controllers/changesets_controller.rb
  app/controllers/diary_entries_controller.rb
  app/controllers/follows_controller.rb
  app/controllers/friendships_controller.rb
  app/helpers/changesets_helper.rb
  app/mailers/user_mailer.rb
  app/models/follow.rb
  app/models/user.rb
  app/views/dashboards/_contact.html.erb
  app/views/dashboards/show.html.erb
  app/views/follows/show.html.erb
  app/views/friendships/make_friend.html.erb
  app/views/friendships/remove_friend.html.erb
  app/views/user_mailer/friendship_notification.html.erb
  app/views/user_mailer/friendship_notification.text.erb
  app/views/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  test/controllers/changesets_controller_test.rb
  test/controllers/diary_entries_controller_test.rb
  test/controllers/follows_controller_test.rb
  test/controllers/friendships_controller_test.rb
  test/controllers/oauth2_authorized_applications_controller_test.rb
  test/factories/follows.rb
  test/factories/friendships.rb
  test/models/user_test.rb
  test/system/dashboard_test.rb
  test/system/follows_test.rb
  test/system/friendships_test.rb
Labels: big-pr

#5520 Include message_read attribute in api output of messages to self
  app/views/api/messages/_message.json.jbuilder
  app/views/api/messages/_message.xml.builder
  test/controllers/api/messages_controller_test.rb
Labels: api

#5533 Use a custom cop to check controller action names
  .rubocop.yml
  .rubocop/specific_action_names.rb
Labels: dx

#5534 Use flash.now for messages to be shown during this request
  .rubocop_todo.yml
  app/controllers/traces_controller.rb
Labels: refactor

#5548 Fix some eslint errors (quotes spacing and parseInt radix) on .js.erb files
  app/assets/javascripts/edit/id.js.erb
  app/assets/javascripts/embed.js.erb
  app/assets/javascripts/osm.js.erb
Labels: refactor

#5556 Drop some legacy browser support code
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/views/layouts/_head.html.erb
  app/views/layouts/_meta.html.erb
  config/initializers/browser.rb
  vendor/assets/polyfill/es6.js
Labels: big-pr

#5560 Remove layersAdded variable from map.updateLayers()
  app/assets/javascripts/leaflet.map.js
Labels: javascript

#5565 Remove IE conditional compilation that limited max features
  app/assets/javascripts/index/layers/data.js
Labels: javascript, mapview

#5566 Remove unused max_features parameter from feature warning
  app/assets/javascripts/index/layers/data.js
Labels: javascript, mapview
