Repository openstreetmap/openstreetmap-website, pull requests merged in 2025-07, with the labels that each got.

#6084 Profile edit tabs
  app/controllers/confirmations_controller.rb
  app/controllers/profiles/companies_controller.rb
  app/controllers/profiles/descriptions_controller.rb
  app/controllers/profiles/images_controller.rb
  app/controllers/profiles/links_controller.rb
  app/controllers/profiles/locations_controller.rb
  app/controllers/profiles/profile_sections_controller.rb
  app/controllers/profiles_controller.rb
  app/views/dashboards/show.html.erb
  app/views/profiles/companies/show.html.erb
  app/views/profiles/descriptions/show.html.erb
  app/views/profiles/images/show.html.erb
  app/views/profiles/links/show.html.erb
  app/views/profiles/locations/show.html.erb
  app/views/profiles/profile_sections/_navigation.html.erb
  app/views/profiles/show.html.erb
  app/views/users/_sidebar_section.html.erb
  app/views/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  test/controllers/profiles/companies_controller_test.rb
  test/controllers/profiles/descriptions_controller_test.rb
  test/controllers/profiles/images_controller_test.rb
  test/controllers/profiles/links_controller_test.rb
  test/controllers/profiles/locations_controller_test.rb
  test/controllers/profiles_controller_test.rb
  test/system/profile_company_change_test.rb
  test/system/profile_description_change_test.rb
  test/system/profile_image_change_test.rb
  test/system/profile_links_change_test.rb
  test/system/profile_location_change_test.rb
  test/system/user_company_test.rb
  test/system/user_location_change_test.rb
Labels: big-pr

#6171 Move integration tests out of api relation controller tests
  test/controllers/api/relations_controller_test.rb
  test/integration/changeset_bbox_test.rb
  test/integration/relation_versions_test.rb
Labels: big-pr

#6196 Clear floats in diary entries
  app/views/diary_entries/_diary_entry.html.erb
  test/system/diary_entry_test.rb
Labels: bug

#6204 Reorder paginated items
  app/controllers/concerns/pagination_methods.rb
  config/routes.rb
  test/controllers/diary_entries_controller_test.rb
Labels: bug

#6191 Configure builtin apps script
  CONFIGURE.md
  lib/tasks/register_oauth_apps.rake
Labels: dx

#5851 Support interactive debugger with docker-compose
  docker-compose.yml
Labels: dx
