Repository openstreetmap/openstreetmap-website, pull requests merged in 2025-02, with the labels that each got.

#5581 Add coordinate precision function
  app/assets/javascripts/index/contextmenu.js
  app/assets/javascripts/index/directions-endpoint.js
  app/assets/javascripts/index/directions.js
  app/assets/javascripts/index/export.js
  app/assets/javascripts/index/query.js
  app/assets/javascripts/index/search.js
  app/assets/javascripts/leaflet.map.js
  app/assets/javascripts/osm.js.erb
  app/assets/javascripts/user.js
Labels: changes requested

#5064 Always do reverse geocoding when routing
  app/assets/javascripts/index/directions-endpoint.js
  app/assets/javascripts/index/directions.js
Labels: javascript

#5613 Fix all no-implicit-globals eslint errors
  app/assets/javascripts/index/directions/fossgis_osrm.js
  app/assets/javascripts/index/directions/fossgis_valhalla.js
  app/assets/javascripts/index/directions/graphhopper.js
  app/assets/javascripts/social_share_button.js
  config/eslint.js
Labels: big-pr

#5626 API element resources - nested elements
  .rubocop.yml
  app/abilities/api_ability.rb
  app/controllers/api/nodes/relations_controller.rb
  app/controllers/api/nodes/ways_controller.rb
  app/controllers/api/relations/relations_controller.rb
  app/controllers/api/relations_controller.rb
  app/controllers/api/ways/relations_controller.rb
  app/controllers/api/ways_controller.rb
  app/views/api/nodes/relations/index.json.jbuilder
  app/views/api/nodes/relations/index.xml.builder
  app/views/api/nodes/ways/index.json.jbuilder
  app/views/api/nodes/ways/index.xml.builder
  app/views/api/relations/relations/index.json.jbuilder
  app/views/api/relations/relations/index.xml.builder
  app/views/api/relations/relations_for_node.json.jbuilder
  app/views/api/relations/relations_for_node.xml.builder
  app/views/api/relations/relations_for_relation.json.jbuilder
  app/views/api/relations/relations_for_relation.xml.builder
  app/views/api/relations/relations_for_way.json.jbuilder
  app/views/api/relations/relations_for_way.xml.builder
  app/views/api/ways/relations/index.json.jbuilder
  app/views/api/ways/relations/index.xml.builder
  app/views/api/ways/ways_for_node.json.jbuilder
  app/views/api/ways/ways_for_node.xml.builder
  config/routes.rb
  test/controllers/api/nodes/relations_controller_test.rb
  test/controllers/api/nodes/ways_controller_test.rb
  test/controllers/api/relations/relations_controller_test.rb
  test/controllers/api/relations_controller_test.rb
  test/controllers/api/ways/relations_controller_test.rb
  test/controllers/api/ways_controller_test.rb
Labels: big-pr

#5645 Create integration tests for element versions
  test/controllers/api/old_nodes_controller_test.rb
  test/controllers/api/old_relations_controller_test.rb
  test/controllers/api/old_ways_controller_test.rb
  test/integration/node_versions_test.rb
  test/integration/way_versions_test.rb
Labels: big-pr

#5649 Refactor API old element redaction tests
  test/controllers/api/old_nodes_controller_test.rb
  test/controllers/api/old_relations_controller_test.rb
  test/controllers/api/old_ways_controller_test.rb
Labels: big-pr

#5668 rerun script/misc/update-wiki-pages
  config/wiki_pages.yml
Labels: big-pr

#5452 API active blocks list
  app/abilities/api_ability.rb
  app/controllers/api/user_blocks/active_lists_controller.rb
  app/controllers/api_controller.rb
  app/views/api/user_blocks/_user_block.json.jbuilder
  app/views/api/user_blocks/_user_block.xml.builder
  app/views/api/user_blocks/active_lists/show.json.jbuilder
  app/views/api/user_blocks/active_lists/show.xml.builder
  app/views/api/user_blocks/show.json.jbuilder
  config/routes.rb
  test/controllers/api/user_blocks/active_lists_controller_test.rb
Labels: api, moderation

#5672 Add option to override Firefox binary used in system tests
  config/settings/test.yml
  test/application_system_test_case.rb
  test/teaspoon_env.rb
Labels: dx

#4301 Add user block api call
  app/abilities/api_ability.rb
  app/controllers/api/user_blocks_controller.rb
  config/locales/en.yml
  config/routes.rb
  lib/oauth.rb
  test/controllers/api/user_blocks_controller_test.rb
Labels: api, moderation

#4926 Home Location page
  app/abilities/ability.rb
  app/assets/javascripts/index.js
  app/assets/javascripts/index/home.js
  app/controllers/accounts/homes_controller.rb
  app/views/accounts/homes/show.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/map.html.erb
  config/locales/en.yml
  config/routes.rb
  test/system/account_home_test.rb
Labels: javascript

#5684 Add option to use headless Firefox in system tests
  config/settings/test.yml
  test/application_system_test_case.rb
  test/teaspoon_env.rb
Labels: dx

#4359 Add changeset comment search api with filtering by author and time
  app/abilities/api_ability.rb
  app/controllers/api/changeset_comments_controller.rb
  app/controllers/api/changesets_controller.rb
  app/controllers/api/notes_controller.rb
  app/controllers/changeset_comments/feeds_controller.rb
  app/controllers/concerns/query_methods.rb
  app/views/api/changeset_comments/_changeset_comment.json.jbuilder
  app/views/api/changeset_comments/_changeset_comment.xml.builder
  app/views/api/changeset_comments/index.json.jbuilder
  app/views/api/changeset_comments/index.xml.builder
  app/views/api/changesets/_changeset.json.jbuilder
  app/views/api/changesets/_changeset.xml.builder
  config/routes.rb
  config/settings.yml
  test/controllers/api/changeset_comments_controller_test.rb
  test/controllers/api/notes_controller_test.rb
Labels: api, changesets

#5558 Replace var in javascript with let/const
  app/assets/javascripts/application.js
  app/assets/javascripts/diary_entry.js
  app/assets/javascripts/embed.js.erb
  app/assets/javascripts/fixthemap.js
  app/assets/javascripts/id.js
  app/assets/javascripts/index.js
  app/assets/javascripts/index/changeset.js
  app/assets/javascripts/index/contextmenu.js
  app/assets/javascripts/index/directions-endpoint.js
  app/assets/javascripts/index/directions.js
  app/assets/javascripts/index/export.js
  app/assets/javascripts/index/history.js
  app/assets/javascripts/index/layers/data.js
  app/assets/javascripts/index/layers/notes.js
  app/assets/javascripts/index/new_note.js
  app/assets/javascripts/index/note.js
  app/assets/javascripts/index/query.js
  app/assets/javascripts/index/search.js
  app/assets/javascripts/leaflet.key.js
  app/assets/javascripts/leaflet.layers.js
  app/assets/javascripts/leaflet.locate.js
  app/assets/javascripts/leaflet.map.js
  app/assets/javascripts/leaflet.note.js
  app/assets/javascripts/leaflet.query.js
  app/assets/javascripts/leaflet.share.js
  app/assets/javascripts/leaflet.sidebar-pane.js
  app/assets/javascripts/leaflet.sidebar.js
  app/assets/javascripts/leaflet.zoom.js
  app/assets/javascripts/matomo.js
  app/assets/javascripts/oauth.js
  app/assets/javascripts/osm.js.erb
  app/assets/javascripts/richtext.js
  app/assets/javascripts/router.js
  app/assets/javascripts/user.js
  app/assets/javascripts/welcome.js
  config/eslint.js
  test/javascripts/osm_test.js
Labels: big-pr

#5278 Display old node versions on map view
  app/assets/javascripts/index.js
Labels: javascript, mapview

#5695 Remove some unnecessary calls to clear the mail queue
  test/controllers/accounts_controller_test.rb
  test/controllers/api/changeset_comments_controller_test.rb
  test/controllers/api/notes_controller_test.rb
  test/controllers/confirmations_controller_test.rb
  test/controllers/diary_comments_controller_test.rb
  test/controllers/follows_controller_test.rb
  test/controllers/messages_controller_test.rb
  test/controllers/passwords_controller_test.rb
  test/controllers/users_controller_test.rb
  test/integration/user_creation_test.rb
  test/system/user_email_change_test.rb
Labels: refactor

#5656 API element resources - redaction paths
  .rubocop.yml
  app/abilities/api_ability.rb
  app/controllers/api/old_elements/redactions_controller.rb
  app/controllers/api/old_elements_controller.rb
  app/controllers/api/old_nodes/redactions_controller.rb
  app/controllers/api/old_relations/redactions_controller.rb
  app/controllers/api/old_ways/redactions_controller.rb
  config/routes.rb
  test/controllers/api/old_nodes/redactions_controller_test.rb
  test/controllers/api/old_nodes_controller_test.rb
  test/controllers/api/old_redactions/redactions_controller_test.rb
  test/controllers/api/old_relations_controller_test.rb
  test/controllers/api/old_ways/redactions_controller_test.rb
  test/controllers/api/old_ways_controller_test.rb
Labels: big-pr

#5713 API changeset resources - index path
  config/routes.rb
  test/controllers/api/changesets_controller_test.rb
  test/controllers/api/relations_controller_test.rb
Labels: big-pr

#5726 API changeset comment visibility resource
  .rubocop.yml
  app/abilities/api_ability.rb
  app/controllers/api/changeset_comments/visibilities_controller.rb
  app/controllers/api/changeset_comments_controller.rb
  app/controllers/api/changesets_controller.rb
  app/views/api/changeset_comments/visibilities/create.json.jbuilder
  app/views/api/changeset_comments/visibilities/create.xml.builder
  app/views/api/changeset_comments/visibilities/destroy.json.jbuilder
  app/views/api/changeset_comments/visibilities/destroy.xml.builder
  app/views/changesets/show.html.erb
  config/routes.rb
  test/abilities/api_capability_test.rb
  test/controllers/api/changeset_comments/visibilities_controller_test.rb
  test/controllers/api/changeset_comments_controller_test.rb
Labels: big-pr
